"""add bookmark unique constraint and clean up table options

Revision ID: 200bc03b970f
Revises: e82d2d28f70d
Create Date: 2026-07-28 19:45:58.024838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '200bc03b970f'
down_revision: Union[str, Sequence[str], None] = 'e82d2d28f70d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'bookmarks', ['user_id'])
    op.create_unique_constraint(None, 'bookmarks', ['course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookmarks', type_='unique')
    op.drop_constraint(None, 'bookmarks', type_='unique')
    # ### end Alembic commands ###
