"""add_technologies_table

Revision ID: 4710c865ca7c
Revises: dd15c5e6fed1
Create Date: 2026-07-12 12:39:58.784777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4710c865ca7c'
down_revision: Union[str, Sequence[str], None] = 'dd15c5e6fed1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('technologies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('about', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technologies_id'), 'technologies', ['id'], unique=False)
    op.create_index(op.f('ix_technologies_name'), 'technologies', ['name'], unique=True)
    op.alter_column('users', 'password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=72),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.String(length=72),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
    op.drop_index(op.f('ix_technologies_name'), table_name='technologies')
    op.drop_index(op.f('ix_technologies_id'), table_name='technologies')
    op.drop_table('technologies')
    # ### end Alembic commands ###
