"""Updated (quizzes,bookmarks) schemas

Revision ID: 83470bf2874e
Revises: 200bc03b970f
Create Date: 2026-07-29 18:00:26.087073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '83470bf2874e'
down_revision: Union[str, Sequence[str], None] = '200bc03b970f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('course_id'), table_name='bookmarks')
    op.drop_index(op.f('user_id'), table_name='bookmarks')
    op.create_unique_constraint('uq_user_course_bookmark', 'bookmarks', ['user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_user_course_bookmark', 'bookmarks', type_='unique')
    op.create_index(op.f('user_id'), 'bookmarks', ['user_id'], unique=True)
    op.create_index(op.f('course_id'), 'bookmarks', ['course_id'], unique=True)
    # ### end Alembic commands ###
