"""Added encrypted password in User table

Revision ID: dd15c5e6fed1
Revises: d7a360d6f46b
Create Date: 2026-07-11 22:26:28.502490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd15c5e6fed1'
down_revision: Union[str, Sequence[str], None] = 'd7a360d6f46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the missing password column with an explicit length for MySQL.
    op.add_column('users', sa.Column('password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###

