"""corrected the foreign key

Revision ID: e82d2d28f70d
Revises: f218b2be84db
Create Date: 2026-07-12 16:07:18.180874

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'e82d2d28f70d'
down_revision: Union[str, Sequence[str], None] = 'f218b2be84db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('technology_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('courses_ibfk_1'), 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'technologies', ['technology_id'], ['id'], ondelete='CASCADE')
    op.drop_column('courses', 'technology_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('technology_name', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key(op.f('courses_ibfk_1'), 'courses', 'technologies', ['technology_name'], ['name'], ondelete='CASCADE')
    op.drop_column('courses', 'technology_id')
    # ### end Alembic commands ###
